### ISSUE TITLE
Error in the typography module documentation

### ISSUE THREAD

**Issue by kikiklang** [heybokeh/pollen-docs#2]
Found a small error in the font size scale table inside the typography module.   

| Property | Value | Equivalent to |
| :--- | :--- | :--- |
| `--scale-3` | `1.5rem` | `34px` |
| `--scale-4` | `1.875rem` | `30px` |
| `--scale-5` | `2.25rem` | `36px` |

Not sure what is the scale you are using here but equivalent pixel size seems off on these rows.  
Nice project btw!.

**Comment by madeleineostoja** [comment]
Good catch! Typo from old values, I'll update them now

**Comment by madeleineostoja** [comment]
Fixed in latest commit, `34px` should be `24px`, other values correct
